// -*- C++ -*-
//
// generated by wxGlade 0.9.3 on Tue Jul  2 04:25:57 2019
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//  Dialog1.cpp Frame1.cpp
//

#ifndef MYFRAME_HPP
#define MYFRAME_HPP

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "gui"    // replace with the appropriate catalog name
#endif

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/wrapsizer.h>
// end wxGlade

// begin wxGlade: ::extracode
#include "strategy/duck_gui.hpp"
#include <vector>
#include <algorithm>
#include <typeinfo>
#include <wx/textctrl.h>
#include <FlyBehavior.hpp>
#include <QuackBehavior.hpp>
// end wxGlade

class MyFrame : public wxFrame
{
public:
	// begin wxGlade: MyFrame::ids
	// end wxGlade

    MyFrame(wxWindow* parent,
	    wxWindowID id,
	    const wxString& title,
	    const wxPoint& pos = wxDefaultPosition,
	    const wxSize& size = wxDefaultSize,
	    long style = wxDEFAULT_FRAME_STYLE);

private:
	// begin wxGlade: MyFrame::methods
	void set_properties();
	void do_layout();
	// end wxGlade

protected:
	// begin wxGlade: MyFrame::attributes
	wxStatusBar* frame_statusbar;
	wxComboBox* ComboBox_ducks;
	wxButton* AddButton;
	wxListBox* ListBox_current_ducks;
	wxButton* RemoveButton;
	wxButton* ClearButton;
	wxRadioBox* RadioBox_quackBehavior;
	wxButton* quackButton;
	wxRadioBox* RadioBox_flyBehavior;
	wxButton* flyButton;
	wxTextCtrl* textCtrl_output;
	wxButton* button_3;
	wxPanel* panel_1;
	wxPanel* panel_2;
	wxNotebook* notebook_1;
	// end wxGlade

    std::vector<G_Duck*> ducks;
    std::vector<QuackBehavior*> quackBehaviors;
    std::vector<FlyBehavior*> flyBehaviors;
    DECLARE_EVENT_TABLE();

public:
	void add_duck_to_listbox(wxCommandEvent &event); // wxGlade: <event_handler>
	void remove_duck_from_list_box(wxCommandEvent &event); // wxGlade: <event_handler>
	void clear_all_ducks_from_list_box(wxCommandEvent &event); // wxGlade: <event_handler>
	void change_quack_behavior(wxCommandEvent &event); // wxGlade: <event_handler>
	void change_fly_behavior(wxCommandEvent &event); // wxGlade: <event_handler>
	void select_current_duck(wxCommandEvent &event); // wxGlade: <event_handler>
	void do_quack(wxCommandEvent &event); // wxGlade: <event_handler>
	void do_fly(wxCommandEvent &event); // wxGlade: <event_handler>
	void update_radioboxes(wxCommandEvent &event); // wxGlade: <event_handler>
	void clear_textctrl_output(wxCommandEvent &event); // wxGlade: <event_handler>
};				   // wxGlade: end class

#endif    // MYFRAME_HPP
